[package]
name = "bankaccountcatalog"
version = "0.3.0"
authors = ["Cosmonic Team"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "bankaccountcatalog"

[dependencies]
async-trait = "0.1"
futures = "0.3"
serde_bytes = "0.11"
serde_json = "1.0"
wasmbus-rpc = "0.14"
wasmcloud-interface-httpserver = "0.11"
rust-embed = "8.0.0"
mime_guess = "2.0.4"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
