apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: bank-account
  annotations:
    version: v0.0.0
    description: "The concordance bank account example"
spec:
  components:
    - name: catalog
      type: actor
      properties:
        image: ghcr.io/cosmonic/cosmonic-gitops/bankaccount_catalog:0.0.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 3
        - type: linkdef
          properties:
            target: httpserver
    - name: httpserver
      type: capability
      properties:
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.2
        contract: wasmcloud:httpserver
