apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-account
spec:
  source:
    path: .
    repoURL: https://github.com/cosmonic/concordance-gitops
    targetRevision: HEAD
    directory:
      recurse: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  project: default
  syncPolicy:
    automated: {}